jadwal/urls.py
from django.urls import path
from . import views


app_name = 'jadwal'

urlpatterns = [
    path('', views.jadwal, name='jadwal'),
    path('<int:pk>/', views.delete, name = 'hapus'),
    # dilanjutkan ...
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jadwal.urls')),
]

jadwal/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
    mata_kuliah = models.CharField(blank=False, max_length= 100)
    dosen = models.CharField(blank=False, max_length= 100)
    jumlah_sks = models.CharField(blank=False, max_length= 100)
    deskripsi = models.CharField(blank=False, max_length= 100)
    semester = models.CharField(blank=False, max_length=100)
    ruang_kelas = models.CharField(blank=False, max_length= 100)

jadwal/forms.py
from django import forms

class formulir(forms.Form):
    mata_kuliah = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Mata Kuliah',
        'type' : 'text',
        'required' : True
    }))
    dosen = forms.CharField(widget=forms.DateTimeInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Dosen',
        'type' : 'text',
        'required' : True
    }))
    jumlah_sks = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Jumlah sks',
        'type' : 'text',
        'required' : True
    }))
    deskripsi = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Deskripsi',
        'type' : 'text',
        'required' : True
    }))
    semester = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Semester',
        'type' : 'text',
        'required' : True
    }))
    ruang_kelas = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Ruang Kelas',
        'type' : 'text',
        'required' : True
    }))

jadwal/views.py
from django.shortcuts import render, redirect
from . import forms, models

# Create your views here.
def jadwal(request):
    if(request.method == "POST"):
        tmp = forms.formulir(request.POST)
        if(tmp.is_valid()):
            tmp2 = models.Jadwal()
            tmp2.mata_kuliah = tmp.cleaned_data["mata_kuliah"]
            tmp2.dosen = tmp.cleaned_data["dosen"]
            tmp2.jumlah_sks = tmp.cleaned_data["jumlah_sks"]
            tmp2.deskripsi = tmp.cleaned_data["deskripsi"]
            tmp2.semester = tmp.cleaned_data["semester"]
            tmp2.ruang_kelas = tmp.cleaned_data["semester"]
            tmp2.save()
        return redirect("/")
    else:
        tmp = forms.formulir()
        tmp2 = models.Jadwal.objects.all()
        tmp_dictio = {
            'formulir' : tmp,
            'jadwal' : tmp2
        }
        return render(request, 'jadwal.html', tmp_dictio)

def delete(request, pk):
    if(request.method == "POST"):
        tmp = forms.formulir(request.POST)
        if(tmp.is_valid()):
            tmp2 = models.Jadwal()
            tmp2.mata_kuliah = tmp.cleaned_data["mata_kuliah"]
            tmp2.dosen = tmp.cleaned_data["dosen"]
            tmp2.jumlah_sks = tmp.cleaned_data["jumlah_sks"]
            tmp2.deskripsi = tmp.cleaned_data["deskripsi"]
            tmp2.semester = tmp.cleaned_data["semester"]
            tmp2.ruang_kelas = tmp.cleaned_data["semester"]
            tmp2.save()
        return redirect("/")
    else:
        models.Jadwal.objects.filter(pk = pk).delete()
        tmp = forms.formulir()
        tmp2 = models.Jadwal.objects.all()
        tmp_dictio = {
            'formulir' : tmp,
            'jadwal' : tmp2  
        }
        return render(request, 'jadwal.html', tmp_dictio)

jadwal/templates/jadwal.html
{% load static %}

<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'jadwal.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Abel&display=swap" rel="stylesheet">
        <title>Jadwal</title>
    </head>

    <body>
        <div class="judul d-flex">
            <div class="mr-auto p-2">
                <h1>Jadwal Kuliah</h1>
            </div>
            <div class="p-2">
                <h1><a href="https://story4-calmeryan.herokuapp.com">Story 4</a></h1>
            </div>
            
        </div>
        <div class="container">
        <br>
        <br>
        <br>
        <br>    
        <div class="row justify-content-between">
        <div class="col-4">
        <div>
            <form action="" method="POST">
                {% csrf_token %}
                {{ formulir }}
                <div class = "centre-items" style = "margin-top: 2%">
                    <input type = "submit" class="btn btn-primary" value="masukan"> 
                </div>
            </form>
        </div>
        </div>

        <div class="col-7">
        <div class="table-responsive" id="Table">
            
                
            <table class="table table-hover">
                <thead>
                    <div class="jadwal.css">
                    <tr style="color: #192965;">
                        <th scope="col">Mata Kuliah</th>
                        <th scope="col">Dosen</th>
                        <th scope="col">Jumlah sks</th>
                        <th scope="col">Deskripsi</th>
                        <th scope="col">Semester</th>
                        <th scope="col">Ruang Kelas</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                {% for i in jadwal %}
                <tbody>
                    <tr>
                        <td>{{i.mata_kuliah}}</td>
                        <td>{{i.dosen}}</td>
                        <td>{{i.jumlah_sks}}</td>
                        <td>{{i.deskripsi}}</td>
                        <td>{{i.semester}}</td>
                        <td>{{i.ruang_kelas}}</td>
                        <td>
                            <a  href = "{% url 'jadwal:hapus' pk=i.pk %}">
                                <button class="btn btn-icon btn-danger">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </a>
                        </td>
                        <td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
            
        </div>
        </div>
        </div>
        </div>
    </body>
</html>